<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Resources\if-advantage-nearby-1034361_88844.ico</ApplicationIcon>
    <PackageIcon>Wilnichols-Alumin-Folders-IOS-Icons-Black-Folder.128.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\if-advantage-nearby-1034361_88844.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RetrieveOneMap\RetrieveOneMap.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Wilnichols-Alumin-Folders-IOS-Icons-Black-Folder.128.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>